### ISSUE TITLE
Wasm module

### ISSUE THREAD

**Issue by craigmulligan** [umgefahren/cook-with-rust#3]
Hey,

I was just looking to compiling this into a wasm module so I can use it in node/web/deno. I had a go at trying to use `wasm-pack` and sprinkling some `#[wasm_bindgen]` around but I'm not really sure what I'm doing :laughing: . Do you have an idea of what it would take to compile this to wasm?  

Thanks!

**Comment by umgefahren** [comment]
If I understand you correctly you have problems compiling the library to a `wasm` target.
I think I can help you with that, although I'm not that familiar with JS and everything that belongs to that.
The essential crate `cook-with-rust-parser` has been updated in the last version to support WASM. Because the crate generates UUIDs the crate has to generate random numbers over the browser API. To enable that, you just have to enable the feature `wasm`.
In the documentation of the crate the feature is described: https://docs.rs/crate/cook-with-rust-parser/0.0.5/features
Your entry in `Cargo.toml` has to look like this:
`cook-with-rust-parser = {version = "0.0.5", features = ["wasm"] }`
You probably still need to write a small wrapper to use the library from JS. For that I would recommend taking a look at the [book of Rust for WASM](https://rustwasm.github.io/book/).

**Comment by craigmulligan** [comment]
Thanks I'll take a look :+1:
